
services:
  backend:
    image: oceanica_backend:latest
    container_name: oceanica_backend
    ports:
      - "8000:8000" 
    env_file:
      - .env.backend
  bot:
    image: oceanica_bot:latest
    container_name: oceanica_bot
    ports:
      - "8080:8080" 
    env_file:
      - .env.bot
    depends_on:
      - backend

